### ISSUE TITLE
"Predictions file is too large" error in challenge submission

### ISSUE THREAD

**Issue by liutianlin0121** [jleuschn/dival#36]
Hi Johannes,

I met a curious problem when submitting the prediction zip file to the challenge website https://lodopab.grand-challenge.org/  After I uploaded the prediction zip file and pressed the "save" button, an error "Predictions file is too large" occurs. This seems unusual because previously I made several submissions, where the prediction files were generated with the same piece of code. The zip file that I wish to submit is 1.9 GB in size (is this a normal size?). Could there be a problem with the challenge website? Thank you!

Cheers,
Tianlin

**Comment by jleuschn** [comment]
Hi Tianlin,

yes, ~2 GB is the normal size. I also get the same message, to me it seems that the maximum allowed file size has been reduced. I contacted the support and will let you know.

Best regards,
Johannes

**Comment by jleuschn** [comment]
Update: the grand challenge team will address this, by end of the month submission should be possible again. If you would like to get the results before, please feel free to send me the submission file in some other way, then I'll evaluate it locally and upload it on behalf of your user account when possible.

Best, Johannes

**Comment by liutianlin0121** [comment]
Thanks a lot!
